# Generated by Django 4.2.4 on 2024-01-07 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Creature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('HP', models.IntegerField()),
                ('STR', models.IntegerField()),
                ('DEX', models.IntegerField()),
                ('WIL', models.IntegerField()),
                ('armor', models.IntegerField(blank=True, null=True)),
                ('attack1', models.CharField(blank=True, max_length=60)),
                ('attack2', models.CharField(blank=True, max_length=60)),
                ('crit', models.TextField(blank=True)),
                ('special', models.TextField(blank=True)),
            ],
        ),
    ]
