# Generated by Django 4.2.4 on 2024-01-07 14:13

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('creatures', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creature',
            name='special',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
